# Generated by Django 5.0.2 on 2024-03-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='calaries',
            new_name='calories',
        ),
    ]
